### ISSUE TITLE
Tests fail with AnalyticalException not raised when settings are not set

### ISSUE THREAD

**Issue by jmwilliams** [jcassee/django-analytical#34]
======================================================================
FAIL: test_no_site_id (analytical.tests.test_tag_clicky.ClickyTagTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "build/bdist.macosx-10.8-intel/egg/analytical/tests/utils.py", line 80, in inner
    return test_func(*args, **kwargs)
  File "build/bdist.macosx-10.8-intel/egg/analytical/tests/test_tag_clicky.py", line 36, in test_no_site_id
    self.assertRaises(AnalyticalException, ClickyNode)
AssertionError: AnalyticalException not raised

======================================================================
FAIL: test_no_account_number (analytical.tests.test_tag_crazy_egg.CrazyEggTagTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "build/bdist.macosx-10.8-intel/egg/analytical/tests/utils.py", line 80, in inner
    return test_func(*args, **kwargs)
  File "build/bdist.macosx-10.8-intel/egg/analytical/tests/test_tag_crazy_egg.py", line 29, in test_no_account_number
    self.assertRaises(AnalyticalException, CrazyEggNode)
AssertionError: AnalyticalException not raised

======================================================================
FAIL: test_no_property_id (analytical.tests.test_tag_google_analytics.GoogleAnalyticsTagTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "build/bdist.macosx-10.8-intel/egg/analytical/tests/utils.py", line 80, in inner
    return test_func(*args, **kwargs)
  File "build/bdist.macosx-10.8-intel/egg/analytical/tests/test_tag_google_analytics.py", line 35, in test_no_property_id
    self.assertRaises(AnalyticalException, GoogleAnalyticsNode)
AssertionError: AnalyticalException not raised

----------------------------------------------------------------------
Ran 191 tests in 0.435s

FAILED (failures=3)

**Comment by jcassee** [comment]
Hi Jimi, is this still an issue? Could you tell me a bit more about your use-case? Those tests run fine on the Python/Django versions specified in `tox.ini`.

**Comment by bittner** [comment]
Closing this issue due to inactivity. If this is reproducible somehow, @jmwilliams, please reopen and update the description with more details.
